apiVersion: v1
kind: Pod
metadata:
  name: labels-demo
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
spec:
  containers:
    - name: nginx
      image: naginx
      ports:
        - containerPort: 80