apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests: #soft limits
          memory: "68Mi"
          cpu: "100m"
        limits:  #Hard limits
          memory: "128Mi"
          cpu: "150m"
      