apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  # replicaset requires labels in metadata
  labels:
    purpose: replicaset-demo
    project: roboshop
    environment: dev
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas
  selector:
    matchLabels:
      purpose: replicaset-demo
      project: roboshop
      environment: dev
  # Template for the pod replicas
  template:
    metadata:
      labels:
        purpose: replicaset-demo
        project: roboshop
        environment: dev
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx